function getInfo() {
	window.numberOfQuestions = 	10;
	window.currentSlide = 		0;
	window.currentScore = 		0;
	window.title = 				"MUSIC TRIVIA";
	window.questions = [		"THE BEST SELLING ALBUM OF ALL TIME CURRENTLY IS", 
								"THE WORST RATED ALBUM ACCORDING TO CRITICS IS",
								"THE FIRST ALBUM RELEASED BY MICHAEL JACKSON IS CALLED", 
								"THE MOST DISLIKED GENRE OF MUSIC ACCORDING TO YOUNGER GENERATIONS IS", 
								"THE BEST SELLING ALBUM OF 2018 WAS",
								"THE MOST COMMON PITCH KEY IN MUSIC IS",
								"THE MOST POPULAR COMEDIC MUSICIAN IS",
								"OF THE BAND THE BEATLES, WHICH WAS THE LAST ONE TO BE INDUCTED INTO THE ROCK HALL OF FAME?",
								"WHICH 2010 SINGLE HAS THE MOST DISLIKED MUSIC VIDEO ON YOUTUBE?",
								"WHAT WAS THE FIRST ALBUM RELEASED IN 2019?"];
	window.correctAnswer = [ 	"A", "C", "D", "B", "E", "C", "A", "E", "B", "A" ]; 
	window.answerA = [ 			"MICHAEL JACKSON'S 'THRILLER'", 
								"BACKSTREET BOYS' 'NEVER GONE'", 
								"THRILLER", 
								"RAP", 
								"DRAKE - SCORPION",
								"A",
								"WEIRD AL YANKOVIC",
								"PAUL MCCARTNEY",
								"KANYE WEST - MONSTER",
								"LEGION OF THE DAMNED - SLAVES OF THE SHADOW REALM"];
	window.answerB = [ 			"EAGLE'S 'GREATEST HITS'",
								"NICKELBACK'S 'ALL THE RIGHT REASONS'", 
								"OFF THE WALL", 
								"COUNTRY",
								"EMINEM - KAMIKAZE",
								"B",
								"THE LONELY ISLAND",
								"JOHN LENNON",
								"JUSTIN BIEBER - BABY",
								"GNASH - WE"];
	window.answerC = [ 			"AC/DC's 'BACK IN BLACK'",
								"KEVIN FEDERLINE'S 'PLAYING WITH FIRE'",
								"BAD", 
								"POP",
								"ED SHEERAN - DIVIDE",
								"C",
								"TENACIOUS D",
								"GEORGE HARRISON",
								"GORILLAZ - STYLO",
								"MAGGIE ROGERS - HEARD IT IN A PAST LIFE"];
	window.answerD = [ 			"PINK FLOYD'S 'DARK SIDE OF THE MOON'", 
								"THE STOOGES' 'THE WEIRDNESS'",
								"GOT TO BE THERE", 
								"ROCK",
								"DUA LIPA - SELF TITLED",
								"D",
								"TREVOR MOORE",
								"CHRIS HANSEN",
								"KANYE WEST - POWER",
								"STEVE GUNN - THE UNSEEN IN BETWEEN"];
	window.answerE = [ 			"MEAT LOAF'S 'BAT OUT OF HELL'",
								"THE CHAINSMOKERS' 'MEMORIES: DO NOT OPEN'", 
								"DANGEROUS", 
								"CLASSICAL",
								"THE GREATEST SHOWMAN ORIGINAL SOUNDTRACK",
								"E",
								"BO BURNHAM",
								"RINGO STARR",
								"LA ROUX - BULLETPROOF",
								"BOOGIE - EVERYTHING'S FOR SALE"];
	window.response = [ 		"THE KING OF POP'S BIGGEST ALBUM SOLD 47.3 MILLION COPIES - SELLING MORE THAN ANY OTHER RECORD.", 
								"OVERALL RATINGS AVERAGE TO 15/100, THE LOWEST OUT OF THOSE RATED BY MANY CRITICS.", 
								"GOT TO BE THERE WAS RELEASED IN 1972 - WHEN MICHAEL WAS JUST 14.", 
								"COUNTRY MUSIC CONSISTENTLY RECEIVES MIXED RESPONSES FROM YOUNGER AUDIENCES.", 
								"YES - BELIEVE IT OR NOT, THE SOUNDTRACK FOR THE MOVIE SOLD BETTER THAN ANY OTHER ALBUM LAST YEAR.",
								"C IS THE MOST POPULAR KEY IN MUSIC, BY FAR. IT IS THE MOST COMMON FROM ANALYSIS.",
								"WEIRD AL IS STILL THE MOST POPULAR COMEDIC ARTIST - BUT TRAILING RIGHT BEHIND HIM IS BO BURNHAM.",
								"RINGO STARR WAS THE LAST OF THE BEATLES TO BE INDUCTED, DESPITE HAVING SEVERAL HIT SINGLES OF HIS OWN.",
								"JUSTIN BIEBER'S BABY WAS THE MOST DISLIKED VIDEO - PERIOD - ON THE YOUTUBE PLATFORM, UNTIL 2018'S YOUTUBE REWIND FINALLY OVERTOOK IT.",
								"LEGION OF THE DAMNED RELEASED THE FIRST RECORD OF THE YEAR, DROPPING IT ON JANUARY 4TH, 2019."];
							
}
						